### ISSUE TITLE
Help needed deploying with data persistence

### ISSUE THREAD

**Issue by PaoloneM** [kiegroup/optaweb-employee-rostering#252]
I'm trying to deploy and run employee rostering starter application with persistent data storage.

I build the project with the following:
```
mvn clean install -DskipTests  -Dorg.optaweb.employeerostering.persistence.datasource=sampleDS -Dorg.optaweb.employeerostering.persistence.dialect=org.hibernate.dialect.MySQL5Dialect
```

On my Wildfly instance I've a datasource named `sampleDS` that is connected to a MySql server and inside it there's a db called "optaweb".
When I deploy .war file via Wildfly admin interface, on my db 13 tables are created, then in the `hibernate_sequence` table ten records are created and keep incrementing until the deploy procedures exits for timeout.

Am I missing something?

**Comment by Christopher-Chianelli** [comment]
Since you are using `MySQL`, you need to uncomment a property in persistence.xml: https://github.com/kiegroup/optaweb-employee-rostering/blob/master/employee-rostering-server/src/main/filtered-resources/META-INF/persistence.xml. Hibernate uses a Table by default for calculating Id's (which is very slow and hence the timeout). Uncommenting the property make it use  MySQL native Id generator (which is much faster).

**Comment by PaoloneM** [comment]
Thanks a lot  @Christopher-Chianelli, uncommenting [this property](https://github.com/kiegroup/optaweb-employee-rostering/blob/a4109df10a817804cae8fb8890d3720c1a09a7a0/employee-rostering-server/src/main/filtered-resources/META-INF/persistence.xml#L21) allowed me to deploy the compiled target to Wildfly with MySql persistence.
