### ISSUE TITLE
Clarify policy for PRs from downstream for constraint rules / business logic

### ISSUE THREAD

**Issue by LoneRifle** [kiegroup/optaweb-employee-rostering#385]
Hello,

I would like to understand what the dev team here feels about accepting changes to this codebase from downstream that deals with business logic and constraint rules. We have written opengovsg#30 that we feel might be helpful to other users, but we are not sure whether this is something you would like to take on

**Comment by LoneRifle** [comment]
@ge0ffrey - would you be happy to comment on this?

**Comment by ge0ffrey** [comment]
Hi @LoneRifle,

We welcome contributions. We have a good number of bugfix and small enhancement contributions for optaplanner, but we would love to see more external contributors that develop entire features.

That being said, at the same time, we need to make sure that any feature added upstream is for the good of the user base, not a specific user. Let me give an example: Adding a constraint like "contract maximum hours per week" (which we did recently), is a feature that is good for the user base. Adding a constraint like "Guards with the skill martial arts must be assigned a training shift alltogether once a week" is good for only specific user(s) - but the complexity it brings for the user base doesn't outweigh it's benefit for those user(s). Sometimes abstracting the constraint can help, but it must still remain obvious to what it does.

The target audience of optaweb-employee-rostering include nurse planning, guard planning, call-center planning, ... but we do expect customizations to be needed, because every hospital plans slightly different than other hospitals. **Our goal is to to get all ubiquitous constraints**: those constraints that occur with at least 25% of the users, should be there out of the box (unless it kills the simplicity of the model, which is rare).

Anyway, @LoneRifle please do feel welcome.  To get started, I suggest opening a conversation on our google group with a list of the constraint features you want to add:
  https://groups.google.com/forum/#!forum/optaplanner-dev
That way we can discuss which ones are clearly ubiquitous and accept those first. @yurloc will probably take over the conversation from me - if he agrees, its good for me and he'll handle your merges. Let's start with the low hanging fruit. Wdyt?

We can also jump on a conf call. @yurloc and me are in CET, @Christopher-Chianelli is in EST.

**Comment by LoneRifle** [comment]
We'll be in touch via Google Groups in due course. 

Ahead of time, you may want to review opengovsg#30; this is the feature we hope you want to accept (in effect, this adds the notion of heavy-duty shifts and prevents the scheduling of heavy duty shifts to the same person within a 72 hour period).

Of course, if right off the bat you don't think you want this, feel free to reply here. I'll close the issue for now since the original issue (the question) has been answered.

Thanks for fielding my query!

**Comment by LoneRifle** [comment]
I've opened a thread at https://groups.google.com/forum/#!topic/optaplanner-dev/atmMsfCFGq0
