### ISSUE TITLE
Cannot create Shifts

### ISSUE THREAD

**Issue by vandlol** [kiegroup/optaweb-employee-rostering#459]
I just started some example tenants, also tried a custom one.
I cannot create a shift when clicking "create shift" in schedule or adjustment menu when Ii hit save nothing happens. Also, cannot create shifts via API...
Anything broken here?

**Comment by Christopher-Chianelli** [comment]
I cannot reproduce the issue; I was able to successfully add Shifts in both the Scheduling and Adjustments screens. Did you fill in the following fields: Shift Start, Shift End, Spot? You might have selected a date range that is out of view, or might of accidentally created a 0-hour duration shift by selecting the same date twice, instead of the date and the date + 1 to create a full day shift. (If you have the same date, you need to change the time so the start time and end time are different).

**Comment by vandlol** [comment]
<img width="784" alt="Screen Shot 2020-07-06 at 21 40 45" src="https://user-images.githubusercontent.com/35688248/86633890-7fb72300-bfd1-11ea-9cc8-0e81a03f5175.png">
<img width="2213" alt="Screen Shot 2020-07-06 at 21 39 55" src="https://user-images.githubusercontent.com/35688248/86633905-834aaa00-bfd1-11ea-940c-e17d20f93b46.png">

did everything "correct" i guess

**Comment by vandlol** [comment]
running on mac btw, dont know if this could have any impact

**Comment by Christopher-Chianelli** [comment]
You are viewing the Anaesthetics spot, but you added a Shift to the Cardiology spot. To change the displayed Spot in the Scheduling/Adjustment views, click on the top-left select, to the left of the date range selector.

**Comment by vandlol** [comment]
oh my - well this is embarrassing - ok i guess i had the same issue in my custom tenant then...
sorry to have bothered you
