### ISSUE TITLE
Unassigned shifts not penalized

### ISSUE THREAD

**Issue by cgrgrbz** [kiegroup/optaweb-employee-rostering#467]
Hello,

Once the scheduling done or terminated the newly created shifts, unassigned shifts, are not penalized. The same for removing the employee of a assigned shift. Images are from the version 7.40.Final, but problem also occurs in the 7.38 and 7.41 as well.

To demonstrate, directly from the releases without any modification. 

- Added a shift to 25 Tue ( img1) 
- Schedule the solver
- Terminate Early (img2) (also notifications always come up, so need to refresh the page)
- Added a new shift to 26 Wed (img3)

![Opera Snapshot_2020-07-25_103049_localhost](https://user-images.githubusercontent.com/9273955/88451861-e1e1a600-ce62-11ea-9932-32203c76a3f5.png)

![Opera Snapshot_2020-07-25_103124_localhost](https://user-images.githubusercontent.com/9273955/88451875-f32ab280-ce62-11ea-8208-2bc2cde9312c.png)

![Opera Snapshot_2020-07-25_103152_localhost](https://user-images.githubusercontent.com/9273955/88451864-e4440000-ce62-11ea-9636-f3087eb0c06d.png)

**Comment by Christopher-Chianelli** [comment]
Thanks for report. Look like this bug is caused by the following lines:

https://github.com/kiegroup/optaweb-employee-rostering/blob/e4b10c5f53f375a616157a208038ff4463506510/optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/service/roster/RosterService.java#L180-L186

https://github.com/kiegroup/optaweb-employee-rostering/blob/e4b10c5f53f375a616157a208038ff4463506510/optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/service/roster/RosterService.java#L270-L274

Note `solverManager.getRoster(tenantId)` returns the *old, stale* roster if the Solver is *not* solving. This issue is fixed in https://github.com/kiegroup/optaweb-employee-rostering/pull/468
