### ISSUE TITLE
Better termination conditions?

### ISSUE THREAD

**Issue by pixnbit** [kiegroup/optaweb-employee-rostering#501]
First off thank you for this amazing repo, we were able to use all the models and constraints for our application. We didn't need the web and also the Spring framework. We use Ktor to run the scheduling, worked out pretty well so far in our testings. We augment the constraints with labor costs and employee attendance rates. However I feel there's a lot that can be improved with how the optimization is terminated. I read about the documentation on [Termination](https://docs.optaplanner.org/7.43.1.Final/optaplanner-docs/html_single/index.html#termination), but not exactly sure about how they can be applied to Employee rostering.

I know this repo either has a fixed amount of time to terminate or calling earlyTerminiate. Neither is ideal, if I have a short duration, some complex schedules won't get shifts assigned. We've seen that already in our testing, but we also don't want everyone running at a longer time, which also costs our computation resources. 

Any guidance on how we can have a good termination condition? Can you comment on the following conditions for the use case of employee rostering?

unimprovedSpentLimit
unimprovedScoreDifferenceThreshold
unimprovedStepCountLimit
bestScoreFeasible

Thank you!

**Comment by pixnbit** [comment]
Some of my investigations:

"bestScoreFeasible" doesn't work it, it probably stops at when all hard constraints are satisfied. Medium "assign every shift" didn't get improved at all. 

"unimprovedSpentLimit" and their variants look promising but didn't yield better results:

```xml
  <termination>
    <millisecondsSpentLimit>1000</millisecondsSpentLimit>
  </termination>
```

run for just 1 second produces:

```json
{
            "soft": 249200,
            "medium": -1,
            "hard": 0
        }
```

```xml
  <localSearch>
    <termination>
      <unimprovedSecondsSpentLimit>10</unimprovedSecondsSpentLimit>
<!--      <unimprovedScoreDifferenceThreshold>1hard/*soft</unimprovedScoreDifferenceThreshold>-->
    </termination>
  </localSearch>
```

running with significantly more time, produces

```json
{
            "soft": 244400,
            "medium": -1,
            "hard": 0
        }
```

**Comment by Christopher-Chianelli** [comment]
bestScoreFeasible - this will terminate solving on the first feasible solution. Not ideal by itself, since no/little optimization will be done on the soft constraints. More useful if combined as "AND" with other conditions (ex: you might want to terminate solving after 1 hour, but ONLY IF the solution is feasible).

unimprovedScoreDifferenceThreshold - this will terminate solving if the score doesn't improve by X after Y amount of time. You can use it to make solving terminate if the soft score doesn't improve by 10 points in 1 hour.

unimprovedSpentLimit - this will terminate solving if the score doesn't improve after Y amount of time. You can use it to make solving terminate if no improvement is gained within 1 hour.

unimprovedStepCountLimit - this will terminate solving if no improvements is made after Y amount of steps. A step is the act of OptaPlanner picking and performing a move, so the amount of time it takes to terminate is dependent on CPU speed. This is good for reproducibility, but not good if you have specific time constraints in mind.

What I would do a OR of the following:

- Have a large `spentLimit` that represent the maximum amount of time you want to spend solving (example: a day). This is to guard against the case OptaPlanner keep finding better and better solutions.
- Have a `unimprovedSpentLimit` for a shorter time, so that if OptaPlanner doesn't find a better solution in 30 minutes, then you can terminate solving early so you don't waste computational resources.

Ultimately, this depends on your particular use case and what your constraints for when and how long you solve are.

**Comment by Christopher-Chianelli** [comment]
The fact that "assign every shift" didn't get improved at all might mean it is impossible to schedule every shift in your particular roster, either due to PTO requests or a lack of employees. To see if this is the case, try adding a single Employee to your roster; if OptaPlanner is able to find a solution with 0 medium constraints broken in the same amount of time with the added Employees, then it might be the case that the original roster was impossible to solve (or very difficult to solve). If it still -1 medium, then you need to keep solving for longer.

**Comment by pixnbit** [comment]
Thanks for your explanation! "bestScoreFeasible" doesn't do what it's supposed to and also trying to improve the medium scores:

Same problem facts (all our data size is small for now just for testing) with a total of 17 shifts,

Running limit 1 second 
  <termination>
    <millisecondsSpentLimit>1000</millisecondsSpentLimit>
  </termination>

improved medium score from -17 to -1

But bestScoreFeasible almost stopped immdiately with out changing medium score at all, it came out -17 still

  <termination>
    <bestScoreFeasible>true</bestScoreFeasible>
  </termination>

**Comment by Christopher-Chianelli** [comment]
Medium is type of soft constraint, not a type of hard constraint, so medium score DOES NOT impact feasibility. You can remove the constraint and remove the `nullable=true` from
https://github.com/kiegroup/optaweb-employee-rostering/blob/a71393faf4fcfd08528d9b2d4ab8a9bb45cd98c5/optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/domain/shift/Shift.java#L69
(Which would make assigning an Employee to every Shift a hard constraint, but make it impossible to do over-constrained planning).

**Comment by pixnbit** [comment]
Thank you for point this out! I'll keep playing with it. At the same time, I feel it would be great to have one general adaptive termination condition for different sizes of employee scheduling to cover 90% use cases. A smaller sized schedule runs for less time and stops earlier, a larger sized schedule runs for more time. I know it's up to us to implement our own logic, but it's also a common requirement probably for most of the similar applications (we share the same models and constraints etc)

**Comment by Christopher-Chianelli** [comment]
That is known as a Hyperheuristic (that is, dynamically adjusting the solver configuration based on the "difficulty" of the problem). https://docs.optaplanner.org/latest/optaplanner-docs/html_single/index.html#hyperheuristics

We do not support hyperheuristic natively yet, so you would need to come up with several different solver configurations, and pick one based on your data set.

IMO, how and when solving is done across different companies, and what standards they want to achieve, are too varied to put a single set of "good" termination conditions on (different people have different definitions of "good"). And then we would need to represent it in the UI somehow (which is difficult for the more complex termination conditions, and if we use hyperheuristics, we need to know what configuration we are using).

**Comment by pixnbit** [comment]
This is a great direction with the hyperheuristic. I'll be looking into coming up with a strategy, something like (shifts * avaialbilities * employees * roles * )

**Comment by pixnbit** [comment]
@Christopher-Chianelli do you know when hyperheuristics will be supported? Any timeline?

**Comment by Christopher-Chianelli** [comment]
@pixnbit The corresponding issue JIRA is https://issues.redhat.com/browse/PLANNER-267 ; We are currently focusing on different issues ATM. What I said above still stands: you can implement hyperheuristics by using different SolverConfigs depending on the problem (either by programmatically configuring the SolverConfig or having a set of solver config files).
