### ISSUE TITLE
In adjust page (CurrentShiftRosterPage.tsx), why WeekPicker's maxDate is this.props.rosterState.firstDraftDate?

### ISSUE THREAD

**Issue by JiangWeian** [kiegroup/optaweb-employee-rostering#512]
<WeekPicker
            aria-label="Select Week to View"
            value={startDate}
            minDate={this.props.rosterState ? this.props.rosterState.lastHistoricDate : undefined}
            maxDate={this.props.rosterState ? this.props.rosterState.firstDraftDate : undefined}

Is this value set reasonably?

**Comment by Christopher-Chianelli** [comment]
Because you are only adjusting published shifts. Published shifts are shifts that occur before the first draft shift, and represent a schedule that is already published to Employees (whereas draft shifts are not published to employees and is only known to the scheduler). There are three periods: Historic (in the past), Published (current to first draft date) and Draft (after first draft day)
