### ISSUE TITLE
After the front-end is published to IIS, how to modify the back-end address?

### ISSUE THREAD

**Issue by JiangWeian** [kiegroup/optaweb-employee-rostering#516]

**Comment by JiangWeian** [comment]
@Christopher-Chianelli , Do you know the answer? I don't know how to connect the back-end address after publishing the front-end.

**Comment by Christopher-Chianelli** [comment]
Modify this line to the public backend url (without the rest prefix):
https://github.com/kiegroup/optaweb-employee-rostering/blob/ab48823f63fc743e2ce142a9dcdc6b068a4a213a/optaweb-employee-rostering-frontend/.env#L1

**Comment by JiangWeian** [comment]
@Christopher-Chianelli , modify this config to take effect need rebuild front-end?

**Comment by Christopher-Chianelli** [comment]
Yes; this constant is baked into the output javascript files at build time.

**Comment by JiangWeian** [comment]
@Christopher-Chianelli ,OK, but I think it is inconvenient to recompile the front-end every time the back-end address changes.

**Comment by Christopher-Chianelli** [comment]
Well, ideally you either have it point to a load balancer (which then redirects to the appropriate back end server) or you serve the frontend on the backend server (in which case no recompile is needed, since it will reuse the same URL) or you set up your domain name server so that requests without `/rest` go to the frontend server, requests with `/rest` go to the backend server.

The only alternative to bundling it at build time is having the user enter the back end url themselves, which is error-prone and unintuitive. (JavaScript is run on the client machine, not the server, so it cannot read environment variables to modify the backend address.)
