### ISSUE TITLE
Can the unique key constraint of  additional_skill_set_id  field be removed?In the table of time_bucket_additional_skill_set

### ISSUE THREAD

**Issue by JiangWeian** [kiegroup/optaweb-employee-rostering#541]
This constraint causes me to create timebuckets of different periods, but cannot select the same skill. This is unreasonable. 
If I forcibly remove constraints from the database and insert duplicate values, will the scheduling result be incorrect?

**Comment by Christopher-Chianelli** [comment]
https://github.com/kiegroup/optaweb-employee-rostering/blob/735263f2d13ed9b4e370f1348783b1a9360a428c/optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/domain/rotation/TimeBucket.java#L52-L53

Should probably use a `@ManyToMany` like
https://github.com/kiegroup/optaweb-employee-rostering/blob/735263f2d13ed9b4e370f1348783b1a9360a428c/optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/domain/spot/Spot.java#L45-L50

instead of `@OneToMany`. I'll check this issue
