### ISSUE TITLE
Shift object does not turn red when the max_minutes constraint is violated

### ISSUE THREAD

**Issue by lorenzobusin** [kiegroup/optaweb-employee-rostering#776]
It could be useful to change the color of the shifts when them exceed the maximum number of minutes for an employee. Maybe I am missing something but checking the length of 'shift.contractMinutesViolationPenaltyList' on 'ShiftEvent.tsx' is always zero while the ScoreDisplay shows correctly the violated max_minutes constraints.

**Comment by Christopher-Chianelli** [comment]
The issue is with how indictments are calculated when there is a group by. This is one of the contract minutes constraints:

```java
    Constraint dailyMinutesMustNotExceedContractMaximum(ConstraintFactory constraintFactory) {
        return constraintFactory.forEach(Employee.class)
                .filter(employee -> employee.getContract().getMaximumMinutesPerDay() != null)
                .join(Shift.class, equal(Function.identity(), Shift::getEmployee))
                .groupBy((employee, shift) -> employee,
                        (employee, shift) -> shift.getStartDateTime().toLocalDate(),
                        sumDuration((employee, shift) -> between(shift.getStartDateTime(), shift.getEndDateTime())))
                .filter((employee, firstDayOfWeek,
                        totalWorkingTime) -> totalWorkingTime.toMinutes() > employee.getContract().getMaximumMinutesPerDay())
                .penalizeConfigurableLong(CONSTRAINT_DAILY_MINUTES_MUST_NOT_EXCEED_CONTRACT_MAXIMUM,
                        (employee, firstDayOfWeek, totalWorkingTime) -> totalWorkingTime.toMinutes()
                                - employee.getContract().getMaximumMinutesPerDay());
    }
``` 

In particular, the following line of code causes the issue:

```java
                .groupBy((employee, shift) -> employee,
                        (employee, shift) -> shift.getStartDateTime().toLocalDate(),
                        sumDuration((employee, shift) -> between(shift.getStartDateTime(), shift.getEndDateTime())))
```

In it, all the `Shift` instances are grouped by their employee and date, and their duration is sum. The resulting stream is `(Employee, LocalDate, Duration)`.  Thus, the Shift instances are no longer in the stream, and a constraint match will not be generated for a Shift (but one will be generated for Employee, LocalDate, and Duration instances).

The front end use the indictment map in order to map constraint violations to shifts. Since the constraint matches for maximum contract minutes do not have shifts, they will not be in the shift's indictment. And because they are not in a shift's indictment, they are reported as 0 for all shifts.

However, there is still an indictment on Employee, which in theory, can be used when generating the ContractMinutesViolation List (basically for each shift, get the indictment of their employee (if the employee is not null), and calculate the ContractMinutesViolation of that).

**Comment by lorenzobusin** [comment]
Thank you!
